Lab #1. Calc
Jeffset/JavaKotlinProgramming pull request #1
Opened 2021-09-15 21:04 UTC by sherri-ice

2021-09-15 21:05 UTC, sherri-ice commented
Known issues after latest commit:

+ Fails if incorrect symbols are entered
+ Fails if there is more than 1 inherited parenthesis expression

*TBC*

2021-09-18 13:27 UTC, Jeffset requested changes

2021-09-18 13:27 UTC, Jeffset commented on lab-01-expr-calc/src/by/sherriice/calc/ParserImpl.java
> +    ArrayList<String> tokens = new ArrayList<>();
Оформив это в виде поля, ты внесла это как _состояние_ (state) объекта. Нужно ли это было делать? Что будет, если мы вызовет `parseExpression` несколько раз чтобы распарсить несколько строк? `tokens` нигде не чистится, оно будет ошибочно хранить старые токены от предыдущего вызова.
Так что стоит перевести это поле в локальную переменную, например вернув её из `ParseTokens`.

2021-09-18 13:27 UTC, Jeffset commented on lab-01-expr-calc/src/by/sherriice/calc/ParserImpl.java
> +    private void ParseTokens(String input) throws ExpressionParseException {
нейминг: методы всегда принято называть с маленькой буквы.

2021-09-18 13:27 UTC, Jeffset commented on lab-01-expr-calc/src/by/sherriice/calc/ParserImpl.java
> +    int start_pos = 0;
Неиспользуемое поле - удалить.

2021-09-18 13:29 UTC, Jeffset commented
Вижу `debugRepresentation()` сделано через виртуальые функции, что ок, но давай всё же попробуем через `Visitor`.
Так же нет вычисления результата выражения :)

Что насчёт остальных пунктов, будешь их делать?

2021-09-18 15:30 UTC, sherri-ice commented
> Что насчёт остальных пунктов, будешь их делать?


Ой да.
Видимо, я невнимательно сделала пул реквест, я думала, что осталось в моём репозитории :)

2021-09-20 06:53 UTC, sherri-ice commented on lab-01-expr-calc/src/by/sherriice/calc/expressions/LiteralImpl.java
> +    String literal;
и же использую дальше literal, присваиваю ему значение, почему final?

2021-09-20 07:14 UTC, sherri-ice commented on lab-01-expr-calc/src/by/sherriice/calc/Parser.java
> +    Map<String, Integer> operationsPriority = new HashMap<>() {{
> 1. Ты же понимаешь, что это поле получилось `static`?

Да, на это и был расчёт. Не хочется создавать каждый раз заново и занимать лишнюю память, когда можно поместить всё в одно место. Я думала сначала выкинуть приоритеты и проверку в какой-нибудь другой вспомогательный класс. 



> * Понимаешь ли ты как она на самом деле работает? :)
Теперь сомневаюсь :)

update: я немного почитала, что создаётся анонимный класс и могут возникнуть проблемы со сборщиком мусора, да?





> 3. унести в `ParserImpl`

Не хочется каждый раз создавать мапку.

2021-11-25 08:01 UTC, Jeffset commented
Теперь всё ок. Пока оценка 9. На 10 давай ещё классы визиторов сделаем generic, чтобы они не возвращали Object и мы потом не делали явные касты.

2022-01-02 12:02 UTC, Jeffset commented
Короче, я уверен, что визиторов ты добавила бы, принято, 10.

2022-01-02 12:02 UTC, closed without merging