Lab1
Jeffset/JavaKotlinProgramming pull request #10
Opened 2021-09-24 12:03 UTC by shine-bright-like-a-diamand

2021-12-02 07:19 UTC, Jeffset requested changes
Итого, текущая оценка - 8.
На 9+ нужно поправить замечание с токенами.
На 10 нужно сделать visitor обобщённым (generic) чтобы можно было не возвращать Object а потом кастовать его.

2021-12-02 07:19 UTC, Jeffset commented on lab_1/src/BinaryExpressionImpl.java
> +        this.bin_op_kind = bin_op_kind;
camelCase

2021-12-02 07:19 UTC, Jeffset commented on lab_1/src/ParserImpl.java
> +        ArrayList<Expression> tokens = new ArrayList<>();
Насколько я вижу, мы пытаемся использовать объекты Expression как токены. Например, выражение в скобочках (parenthesis expression) мы можем создать с child, а можем создать как токен. И так же тут много `instanceof` проверок. Предлагается сделать отдельный класс/enum для токенов. А Expression использовать только для toTree.

2021-12-04 18:59 UTC, shine-bright-like-a-diamand commented
add class Token + generic visitor

2021-12-23 06:57 UTC, Jeffset commented
Принято, оценка 10.

2021-12-23 06:57 UTC, closed without merging