Lab_1
Jeffset/JavaKotlinProgramming pull request #11
Opened 2021-09-26 15:53 UTC by mrboorger

Supports addition, subtraction, multiply, division, parenthesis, variables.
Parses the expression, writes the tree debug-representation, tree depth, reads the variables,  writes the result.

2021-09-30 10:03 UTC, mrboorger commented on lab-01-expr-calc/src/VariablesVisitor.java
> +        mVariablesValues.put(name, mScanner.nextDouble());
Добавить поведение, при котором обрабатывается случай некорректного ввода значения переменной

2021-12-02 07:03 UTC, Jeffset requested changes
Всё вроде ок, текущая оценка - 9. 
На 10 нужно доделать generic для visitor, чтобы он не возвращал `Object` и потом кастовать.

2021-12-02 07:03 UTC, Jeffset commented on lab-01-expr-calc/src/BinaryExpression.java
> +        ADDITION('+', "ADD"),
У `enum` и так есть `name`, можно было бы его использовать.

2021-12-02 07:03 UTC, Jeffset commented on lab-01-expr-calc/src/ExpressionParseException.java
> +        super(error_message);
camelCase only

2021-12-25 17:23 UTC, mrboorger commented on lab-01-expr-calc/src/ExpressionParseException.java
> +        super(error_message);
изменено

2021-12-25 17:23 UTC, mrboorger commented on lab-01-expr-calc/src/VariablesVisitor.java
> +        mVariablesValues.put(name, mScanner.nextDouble());
изменено

2021-12-25 17:24 UTC, mrboorger commented
> Всё вроде ок, текущая оценка - 9. На 10 нужно доделать generic для visitor, чтобы он не возвращал `Object` и потом кастовать.

Сделано

2022-01-02 11:33 UTC, Jeffset commented
Принято, 10

2022-01-02 11:33 UTC, closed without merging