Lab-01-expr-calc
Jeffset/JavaKotlinProgramming pull request #2
Opened 2021-09-16 09:35 UTC by Dima-Makarov

2021-09-18 15:28 UTC, Jeffset requested changes

2021-09-18 15:28 UTC, Jeffset commented on lab-01-expr-calc/task.md
> -
А чего это мы решили часть задания удалить? :)

2021-09-18 15:28 UTC, Jeffset commented on lab-01-expr-calc/lab-01/src/MainTest.java
> +        } catch (Exception | ExpressionParseException e) {
Буду спрашивать на паре что это за конструкция.

2021-09-18 15:28 UTC, Jeffset commented on lab-01-expr-calc/lab-01/src/VariableLiteral.java
> +public class VariableLiteral implements Literal {
Странное архитектурное решение. Переменная - это не литерал. Почему мы в `getValue()` можем просто вернуть `0`?

2021-09-18 15:28 UTC, Jeffset commented on lab-01-expr-calc/lab-01/src/exceptions/ExpressionParseException.java
> +public class ExpressionParseException extends Throwable {
nit: `extends Exception` достаточно, `Throwable` не принято.

2021-09-18 15:28 UTC, Jeffset commented on lab-01-expr-calc/lab-01/src/VariableLiteral.java
> +        return 0;
Если мы уже заимплементили интерфейс `Literal`, то тут имеет смысл не возвращать `0` что неверно, а напрямую сказать клиенту этого API, что мы не поддерживаем такую операцию, выбросив `throw new UnsupportedOperationException("can't directly query value of a variable")`. Это в теории, тут просто не стоило имплементить `Literal`.

2021-09-18 16:27 UTC, Dima-Makarov commented on lab-01-expr-calc/lab-01/src/exceptions/ExpressionParseException.java
> +public class ExpressionParseException extends Throwable {
fixed

2021-09-18 16:27 UTC, Dima-Makarov commented on lab-01-expr-calc/task.md
> -
Да какая разница :)

2021-09-18 16:27 UTC, Dima-Makarov commented on lab-01-expr-calc/lab-01/src/MainTest.java
> +    static void EXPECT_EQ(double first, double second) {
fixed

2021-09-18 16:27 UTC, Dima-Makarov commented on lab-01-expr-calc/lab-01/src/Main.java
> +            } catch (ExpressionParseException e) {
fixed

2021-09-18 16:27 UTC, Dima-Makarov commented on lab-01-expr-calc/lab-01/src/Main.java
> +                System.out.println("Something went wrong. Please try again");
fixed

2021-09-18 16:27 UTC, Dima-Makarov commented on lab-01-expr-calc/lab-01/src/LiteralValue.java
> +    double value;
fixed

2021-09-18 16:27 UTC, Dima-Makarov commented on lab-01-expr-calc/lab-01/src/Main.java
> +//        in.close();
да, я забыл про это. Поместил туда куда надо.

2021-09-18 16:27 UTC, Dima-Makarov commented on lab-01-expr-calc/lab-01/src/BraceType.java
> +    close
fixed

2021-09-18 16:27 UTC, Dima-Makarov commented on lab-01-expr-calc/lab-01/src/BraceType.java
> +    open,
fixed

2021-09-18 16:27 UTC, Dima-Makarov commented on lab-01-expr-calc/lab-01/src/BinaryExpressionImpl.java
> +    private final BinOpKind bin_op_kind;
fixed

2021-09-18 16:54 UTC, Dima-Makarov commented on lab-01-expr-calc/lab-01/src/ComputeExpressionVisitor.java
> +    Map<String, Double> variables = new HashMap<>();
исправил всю схему с переменными

2021-09-18 16:55 UTC, Dima-Makarov commented on lab-01-expr-calc/lab-01/src/ComputeExpressionVisitor.java
> +            System.out.print("value for '" + expr.getName() + "': ");
да, вынес в отдельный визитор

2021-09-18 16:55 UTC, Dima-Makarov commented on lab-01-expr-calc/lab-01/src/Main.java
> +    private static String toString(String input) {
поменял

2021-09-18 16:55 UTC, Dima-Makarov commented on lab-01-expr-calc/lab-01/src/ParenthesisExpression.java
> +        return null;
да, так и есть

2021-09-18 16:59 UTC, Dima-Makarov commented on lab-01-expr-calc/lab-01/src/VariableLiteral.java
> +public class VariableLiteral implements Literal {
да, исправил, теперь класс переменной имплементит Expression

2021-09-18 16:59 UTC, Dima-Makarov commented on lab-01-expr-calc/lab-01/src/VariableLiteral.java
> +        return 0;
исправил

2021-09-19 14:17 UTC, Jeffset approved these changes
Ок, принято.

2021-09-19 14:21 UTC, Jeffset commented
ПР закрываем.

2021-09-19 14:21 UTC, closed without merging

2021-12-23 07:04 UTC, Jeffset commented
Оценка 10.