Lab1
Jeffset/JavaKotlinProgramming pull request #4
Opened 2021-09-19 12:28 UTC by Korbut-Anton

Note: unary + and - work only after "(" or at the beginning of a string

2021-09-19 21:05 UTC, Jeffset requested changes

2021-09-19 21:56 UTC, Jeffset commented on lab-01-expr-calc/src/com/javalab1/ParserImpl.java
> +    ArrayList<Pair<String, Lexeme>> result = new ArrayList<>();
nit:  Очень часто лучше предпочесть именованый класс, где будут именованые поля, классам вида `Pair`, `Triple`, и т. п. потому что с первого взгляда непонятно, что first и second в них значат.

2021-09-20 10:43 UTC, Korbut-Anton commented on lab-01-expr-calc/src/com/javalab1/BaseExpression.java
> +          throws Exception {
Добавил новый тип исключения для этого, throws exception теперь нету

2021-09-20 10:43 UTC, Korbut-Anton commented on lab-01-expr-calc/src/com/javalab1/BaseExpression.java
> +  protected BaseExpression createLeftChildIfPossible(Pair<String, ParserImpl.Lexeme> pair)
Тут же просто создание левого и правого ребёнка по строке и токену, т.е. можно с этим программно построить дерево выражений (как при парсинге, так и в другом месте, если вдруг понадобится).

2021-09-20 10:43 UTC, Korbut-Anton commented on lab-01-expr-calc/src/com/javalab1/BinOpKind.java
> +public enum BinOpKind {
Исправлю

2021-09-20 10:43 UTC, Korbut-Anton commented on lab-01-expr-calc/src/com/javalab1/Pair.java
> +  public static <K, V> Pair<K, V> createPair(K first, V second) {
Заменю

2021-09-20 10:43 UTC, Korbut-Anton commented on lab-01-expr-calc/src/com/javalab1/ParserImpl.java
> +    ArrayList<Pair<String, Lexeme>> result = new ArrayList<>();
Ок, но пока оставлю как есть

2021-09-20 10:43 UTC, Korbut-Anton commented on lab-01-expr-calc/src/com/javalab1/ParserImpl.java
> +  private Expression MakeTree(ArrayList<Pair<String, Lexeme>> inputList) throws Exception {
Исправлю

2021-09-20 10:43 UTC, Korbut-Anton commented on lab-01-expr-calc/src/com/javalab1/Tests.java
> +    HashMap<String, Double> hashMap = new HashMap<>();
Исправлю

2021-09-20 10:43 UTC, Korbut-Anton commented on lab-01-expr-calc/src/com/javalab1/Tests.java
> +    assert (Math.abs((double) expr1.accept(new ComputeExpressionVisitor(hashMap)) - 5.0)
Ок

2021-09-20 10:43 UTC, Korbut-Anton commented on lab-01-expr-calc/src/com/javalab1/ToStringExpressionVisitor.java
> +    return new StringBuilder(expr.hasMinus() ? "-" : "").append(expr.getName());
Заменю

2022-01-02 12:19 UTC, Jeffset commented
Принято, 10

2022-01-02 12:19 UTC, closed without merging